name: CI Build

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK ${{ matrix.java }}
              uses: actions/setup-java@v1
              with:
                  java-package: jdk
                  java-version: 1.8

            - name: Make Gradle executable
              if: ${{ runner.os != 'Windows' }}
              run: chmod +x gradlew

            - name: Build using Gradle
              run: ./gradlew setupCIWorkspace build
